/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BOT;

import net.dv8tion.jda.core.AccountType;
import net.dv8tion.jda.core.JDABuilder;
import net.dv8tion.jda.core.entities.Game;

import javax.security.auth.login.LoginException;

public class App {
    private App() {
        try {
            System.out.println("Booting");
            new JDABuilder(AccountType.BOT)
                    .setToken(Secrets.TOKEN)
                    .setAudioEnabled(false)
                    .addEventListener(new Listener())
                    .setGame(Game.streaming("kirito5572's TESTING BOT","https://github.com/kirito5572/Discord_BOT"))
                    .build().awaitReady();
            System.out.println("Running");
        } catch (LoginException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        new App();
    }
}
